from django.urls import path
from ideology.api import views

app_name = "ideology"

urlpatterns = [
    path(
        "structure/complexities/",
        views.AbstractionComplexityListView.as_view(),
        name="complexity-list",
    ),
    path(
        "structure/sections/<str:complexity_uuid>/",
        views.SectionListByComplexityView.as_view(),
        name="section-list-by-complexity",
    ),
    path(
        "structure/sections/<str:section_uuid>/axes/",
        views.AxisListBySectionView.as_view(),
        name="axis-list-by-section",
    ),
    path(
        "structure/conditioners/<str:complexity_uuid>/aggregated/",
        views.ConditionerListAggregatedByComplexityView.as_view(),
        name="conditioner-list-aggregated-by-complexity",
    ),
    path(
        "ideologies/",
        views.IdeologyListView.as_view(),
        name="ideology-list",
    ),
    path(
        "ideologies/<str:uuid>/",
        views.IdeologyDetailView.as_view(),
        name="ideology-detail",
    ),
    path(
        "answers/axis/<str:uuid>/",
        views.UpsertAxisAnswerView.as_view(),
        name="upsert-axis-answer",
    ),
    path(
        "answers/axis/<str:uuid>/delete/",
        views.DeleteAxisAnswerView.as_view(),
        name="delete-axis-answer",
    ),
    path(
        "answers/axis/<str:section_uuid>/list/",
        views.UserAxisAnswerListBySectionView.as_view(),
        name="user-axis-answers-by-section",
    ),
    path(
        "answers/conditioner/<str:uuid>/",
        views.UpsertConditionerAnswerView.as_view(),
        name="upsert-conditioner-answer",
    ),
    path(
        "answers/conditioner/<str:uuid>/delete/",
        views.DeleteConditionerAnswerView.as_view(),
        name="delete-conditioner-answer",
    ),
    path(
        "answers/conditioner/<str:complexity_uuid>/list/",
        views.UserConditionerAnswerListByComplexityView.as_view(),
        name="user-conditioner-answers-by-complexity",
    ),
    path(
        "answers/completed/latest/",
        views.LatestCompletedAnswerView.as_view(),
        name="completed-answer-latest",
    ),
    path(
        "answers/completed/generate/",
        views.GenerateCompletedAnswerView.as_view(),
        name="completed-answer-generate",
    ),
    path(
        "answers/completed/<str:uuid>/",
        views.RetrieveCompletedAnswerView.as_view(),
        name="completed-answer-detail",
    ),
]
