services:
  minio:
    image: minio/minio
    container_name: ${PROJECT_NAME}_minio
    hostname: minio
    restart: always
    volumes:
      - minio_data:/data
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl -f http://127.0.0.1:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      minio:
        condition: service_healthy
