# Generated by Django 6.0 on 2026-01-15 19:02

import uuid

import core.helpers.storage_helpers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ideology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Ideology Name",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description_supporter",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description from the point of view of a supporter",
                        null=True,
                        verbose_name="Supporter description",
                    ),
                ),
                (
                    "description_supporter_es",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description from the point of view of a supporter",
                        null=True,
                        verbose_name="Supporter description",
                    ),
                ),
                (
                    "description_supporter_en",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description from the point of view of a supporter",
                        null=True,
                        verbose_name="Supporter description",
                    ),
                ),
                (
                    "description_detractor",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a detractor",
                        null=True,
                        verbose_name="Detractor description",
                    ),
                ),
                (
                    "description_detractor_es",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a detractor",
                        null=True,
                        verbose_name="Detractor description",
                    ),
                ),
                (
                    "description_detractor_en",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a detractor",
                        null=True,
                        verbose_name="Detractor description",
                    ),
                ),
                (
                    "description_neutral",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a neutral",
                        null=True,
                        verbose_name="Neutral description",
                    ),
                ),
                (
                    "description_neutral_es",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a neutral",
                        null=True,
                        verbose_name="Neutral description",
                    ),
                ),
                (
                    "description_neutral_en",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a neutral",
                        null=True,
                        verbose_name="Neutral description",
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        help_text="Ideology Flag Image",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Flag",
                    ),
                ),
                (
                    "background",
                    models.ImageField(
                        blank=True,
                        help_text="Ideology Background Image",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Background",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Ideology Color Image",
                        max_length=16,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology",
                "verbose_name_plural": "Ideologies",
            },
        ),
        migrations.CreateModel(
            name="IdeologyAbstractionComplexity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The label for this level of abstraction (e.g., 'Concrete', 'Theoretical', 'Metaphysical').",
                        max_length=128,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="The label for this level of abstraction (e.g., 'Concrete', 'Theoretical', 'Metaphysical').",
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The label for this level of abstraction (e.g., 'Concrete', 'Theoretical', 'Metaphysical').",
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the characteristics that define this complexity level.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the characteristics that define this complexity level.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the characteristics that define this complexity level.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "complexity",
                    models.PositiveSmallIntegerField(
                        help_text="A numerical value used to rank and order the levels of abstraction (e.g., 1 for lowest, 10 for highest).",
                        unique=True,
                        verbose_name="Complexity Score",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Abstraction Complexity",
                "verbose_name_plural": "Ideology Abstraction Complexities",
                "ordering": ["complexity"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyAxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name of the axis (e.g., 'Economic Freedom').",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="Internal name of the axis (e.g., 'Economic Freedom').",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Internal name of the axis (e.g., 'Economic Freedom').",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of what this axis measures.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of what this axis measures.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of what this axis measures.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "left_label",
                    models.CharField(
                        help_text="Label for the start or minimum value of the axis (e.g., 'Total Control').",
                        max_length=255,
                        verbose_name="Left Label (0%)",
                    ),
                ),
                (
                    "left_label_es",
                    models.CharField(
                        help_text="Label for the start or minimum value of the axis (e.g., 'Total Control').",
                        max_length=255,
                        null=True,
                        verbose_name="Left Label (0%)",
                    ),
                ),
                (
                    "left_label_en",
                    models.CharField(
                        help_text="Label for the start or minimum value of the axis (e.g., 'Total Control').",
                        max_length=255,
                        null=True,
                        verbose_name="Left Label (0%)",
                    ),
                ),
                (
                    "right_label",
                    models.CharField(
                        help_text="Label for the end or maximum value of the axis (e.g., 'Total Liberty').",
                        max_length=255,
                        verbose_name="Right Label (100%)",
                    ),
                ),
                (
                    "right_label_es",
                    models.CharField(
                        help_text="Label for the end or maximum value of the axis (e.g., 'Total Liberty').",
                        max_length=255,
                        null=True,
                        verbose_name="Right Label (100%)",
                    ),
                ),
                (
                    "right_label_en",
                    models.CharField(
                        help_text="Label for the end or maximum value of the axis (e.g., 'Total Liberty').",
                        max_length=255,
                        null=True,
                        verbose_name="Right Label (100%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Axis",
                "verbose_name_plural": "Ideology Axes",
                "ordering": ["section", "name"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the conditioner or variable.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="The name of the conditioner or variable.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The name of the conditioner or variable.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of what this conditioner measures or defines within an ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of what this conditioner measures or defines within an ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of what this conditioner measures or defines within an ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean (Yes/No)"),
                            ("categorical", "Categorical (Selection)"),
                            ("scale", "Scale (Numeric Range)"),
                            ("numeric", "Numeric Value"),
                            ("text", "Free Text"),
                        ],
                        default="categorical",
                        help_text="Defines the format of the data expected for this conditioner.",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "accepted_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of valid options if the type is 'Categorical'. Format: ['Option A', 'Option B'].",
                        null=True,
                        verbose_name="Accepted Values",
                    ),
                ),
                (
                    "accepted_values_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of valid options if the type is 'Categorical'. Format: ['Option A', 'Option B'].",
                        null=True,
                        verbose_name="Accepted Values",
                    ),
                ),
                (
                    "accepted_values_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of valid options if the type is 'Categorical'. Format: ['Option A', 'Option B'].",
                        null=True,
                        verbose_name="Accepted Values",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Conditioner",
                "verbose_name_plural": "Ideology Conditioners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the religion or belief system.",
                        max_length=128,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="The name of the religion or belief system.",
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The name of the religion or belief system.",
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the religion's core tenets.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the religion's core tenets.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the religion's core tenets.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Religion",
                "verbose_name_plural": "Religions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the tag.",
                        max_length=120,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the tag.",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the tag.",
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the tag.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="The description of the tag.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="The description of the tag.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="CompletedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="Structured JSON containing the full set of answers provided by the user.",
                        verbose_name="Answers Data",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        help_text="The user who submitted this set of answers.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Completed Answer",
                "verbose_name_plural": "Completed Answers",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="The country where this ideology is present or relevant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="cities_light.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology being contextualized.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific region within a country (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="cities_light.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The religion associated with this ideology in this context.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="ideology.religion",
                        verbose_name="Religion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Association",
                "verbose_name_plural": "Ideology Associations",
            },
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Countries where this ideology is explicitly present.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="cities_light.country",
                verbose_name="Associated Countries",
            ),
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific regions where this ideology is explicitly present.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="cities_light.region",
                verbose_name="Associated Regions",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyAxisConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "condition_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "axis",
                    models.ForeignKey(
                        help_text="The axis being conditioned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_rules",
                        to="ideology.ideologyaxis",
                        verbose_name="Axis",
                    ),
                ),
                (
                    "conditioner",
                    models.ForeignKey(
                        help_text="The conditioner determining visibility.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Axis Conditioner",
                "verbose_name_plural": "Ideology Axis Conditioners",
                "ordering": ["axis", "name"],
                "unique_together": {
                    ("axis", "conditioner", "name"),
                    ("axis", "conditioner", "name_en"),
                    ("axis", "conditioner", "name_es"),
                },
            },
        ),
        migrations.AddField(
            model_name="ideologyaxis",
            name="conditioners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditioners that determine if this axis is relevant.",
                related_name="conditioned_axes",
                through="ideology.IdeologyAxisConditioner",
                to="ideology.ideologyconditioner",
                verbose_name="Conditioners",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyConditionerConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "condition_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "source_conditioner",
                    models.ForeignKey(
                        help_text="The conditioner determining visibility.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_conditioner_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Source Conditioner",
                    ),
                ),
                (
                    "target_conditioner",
                    models.ForeignKey(
                        help_text="The conditioner being conditioned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Target Conditioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Conditioner Conditioner",
                "verbose_name_plural": "Ideology Conditioner Conditioners",
                "ordering": ["target_conditioner", "name"],
                "unique_together": {
                    ("target_conditioner", "source_conditioner", "name"),
                    ("target_conditioner", "source_conditioner", "name_en"),
                    ("target_conditioner", "source_conditioner", "name_es"),
                },
            },
        ),
        migrations.AddField(
            model_name="ideologyconditioner",
            name="conditioners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditioners that determine the visibility of this conditioner.",
                related_name="conditioned_by",
                through="ideology.IdeologyConditionerConditioner",
                to="ideology.ideologyconditioner",
                verbose_name="Conditioners",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title or source name (e.g., Book Title, Article Headline, Author Name).",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Contextual details or specific quotes relevant to the ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Contextual details or specific quotes relevant to the ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Contextual details or specific quotes relevant to the ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the source material, if available online.",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology supported or explained by this reference.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology reference",
                "verbose_name_plural": "Ideology references",
            },
        ),
        migrations.CreateModel(
            name="IdeologySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title of the thematic section (e.g., 'Economics', 'Social Structure').",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="The title of the thematic section (e.g., 'Economics', 'Social Structure').",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The title of the thematic section (e.g., 'Economics', 'Social Structure').",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A summary of the topics and concepts covered in this section.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="A summary of the topics and concepts covered in this section.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="A summary of the topics and concepts covered in this section.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Visual representation for this section. SVG or PNG formats are recommended.",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "abstraction_complexity",
                    models.ForeignKey(
                        help_text="The complexity level that groups these sections.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ideology.ideologyabstractioncomplexity",
                        verbose_name="Abstraction Complexity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Section",
                "verbose_name_plural": "Ideology Sections",
                "ordering": ["abstraction_complexity", "name"],
            },
        ),
        migrations.AddField(
            model_name="ideologyaxis",
            name="section",
            field=models.ForeignKey(
                help_text="The thematic section this axis belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="axes",
                to="ideology.ideologysection",
                verbose_name="Section",
            ),
        ),
        migrations.CreateModel(
            name="IdeologySectionConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "condition_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "conditioner",
                    models.ForeignKey(
                        help_text="The conditioner determining visibility.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioner",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The section being conditioned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_rules",
                        to="ideology.ideologysection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Section Conditioner",
                "verbose_name_plural": "Ideology Section Conditioners",
                "ordering": ["section", "name"],
                "unique_together": {
                    ("section", "conditioner", "name"),
                    ("section", "conditioner", "name_en"),
                    ("section", "conditioner", "name_es"),
                },
            },
        ),
        migrations.AddField(
            model_name="ideologysection",
            name="conditioners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditioners that determine the visibility of this section.",
                related_name="conditioned_sections",
                through="ideology.IdeologySectionConditioner",
                to="ideology.ideologyconditioner",
                verbose_name="Conditioners",
            ),
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_religions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Religions linked to this ideology.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="ideology.religion",
                verbose_name="Associated Religions",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology to which this tag belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The specific tag to associate with the ideology.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideology_assignments",
                        to="ideology.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology tag",
                "verbose_name_plural": "Ideology tags",
            },
        ),
        migrations.AddField(
            model_name="ideology",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this ideology.",
                related_name="ideologies",
                through="ideology.IdeologyTag",
                to="ideology.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="UserAxisAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "is_indifferent",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the value is irrelevant/indifferent.",
                        verbose_name="Is Indifferent",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Position Value",
                    ),
                ),
                (
                    "margin_left",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Left Margin Tolerance",
                    ),
                ),
                (
                    "margin_right",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Right Margin Tolerance",
                    ),
                ),
                (
                    "axis",
                    models.ForeignKey(
                        help_text="The specific axis being measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideology.ideologyaxis",
                        verbose_name="Axis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Axis Answer",
                "verbose_name_plural": "User Axis Answers",
            },
        ),
        migrations.CreateModel(
            name="UserConditionerAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("answer", models.CharField(max_length=255, verbose_name="Answer")),
                (
                    "conditioner",
                    models.ForeignKey(
                        help_text="The question or variable being answered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioner_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Conditioner Answer",
                "verbose_name_plural": "User Conditioner Answers",
            },
        ),
        migrations.CreateModel(
            name="IdeologyAxisDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "is_indifferent",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the value is irrelevant/indifferent.",
                        verbose_name="Is Indifferent",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Position Value",
                    ),
                ),
                (
                    "margin_left",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Left Margin Tolerance",
                    ),
                ),
                (
                    "margin_right",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Right Margin Tolerance",
                    ),
                ),
                (
                    "axis",
                    models.ForeignKey(
                        help_text="The specific axis being measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideology.ideologyaxis",
                        verbose_name="Axis",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_definitions",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Axis Definition",
                "verbose_name_plural": "Ideology Axis Definitions",
                "unique_together": {("ideology", "axis")},
            },
        ),
        migrations.CreateModel(
            name="IdeologyConditionerDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("answer", models.CharField(max_length=255, verbose_name="Answer")),
                (
                    "conditioner",
                    models.ForeignKey(
                        help_text="The question or variable being answered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioner",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioner_definitions",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Conditioner Definition",
                "verbose_name_plural": "Ideology Conditioner Definitions",
                "unique_together": {("ideology", "conditioner")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="ideologyaxis",
            unique_together={
                ("section", "name"),
                ("section", "name_en"),
                ("section", "name_es"),
            },
        ),
        migrations.AddConstraint(
            model_name="ideologyassociation",
            constraint=models.UniqueConstraint(
                fields=("ideology", "country", "region", "religion"),
                name="unique_ideology_context_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="ideologyassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country__isnull", False),
                    ("region__isnull", False),
                    ("religion__isnull", False),
                    _connector="OR",
                ),
                name="ideology_association_has_at_least_one_context",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ideologytag",
            unique_together={("tag", "ideology")},
        ),
        migrations.AlterUniqueTogether(
            name="useraxisanswer",
            unique_together={("user", "axis")},
        ),
        migrations.AlterUniqueTogether(
            name="userconditioneranswer",
            unique_together={("user", "conditioner")},
        ),
    ]
