# Generated by Django 6.0 on 2026-01-05 16:27

import uuid

import core.helpers.storage_helpers
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities_light", "0012_city_translations_country_translations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ideology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Ideology Name",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description_supporter",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description from the point of view of a supporter",
                        null=True,
                        verbose_name="Supporter description",
                    ),
                ),
                (
                    "description_detractor",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a detractor",
                        null=True,
                        verbose_name="Detractor description",
                    ),
                ),
                (
                    "description_neutral",
                    models.TextField(
                        blank=True,
                        help_text="Ideology Description the point of view of a neutral",
                        null=True,
                        verbose_name="Neutral description",
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        help_text="Ideology Flag Image",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Flag",
                    ),
                ),
                (
                    "background",
                    models.ImageField(
                        blank=True,
                        help_text="Ideology Background Image",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Background",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Ideology Color Image",
                        max_length=16,
                        null=True,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology",
                "verbose_name_plural": "Ideologies",
            },
        ),
        migrations.CreateModel(
            name="IdeologyAbstractionComplexity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The label for this level of abstraction (e.g., 'Concrete', 'Theoretical', 'Metaphysical').",
                        max_length=128,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of the characteristics that define this complexity level.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "complexity",
                    models.PositiveSmallIntegerField(
                        help_text="A numerical value used to rank and order the levels of abstraction (e.g., 1 for lowest, 10 for highest).",
                        unique=True,
                        verbose_name="Complexity Score",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Abstraction Complexity",
                "verbose_name_plural": "Ideology Abstraction Complexities",
                "ordering": ["complexity"],
            },
        ),
        migrations.CreateModel(
            name="Religion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the religion or belief system.",
                        max_length=128,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the religion's core tenets.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Religion",
                "verbose_name_plural": "Religions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The name of the tag.",
                        max_length=120,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the tag.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="CompletedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="Structured JSON containing the full set of answers provided by the user.",
                        verbose_name="Answers Data",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        help_text="The user who submitted this set of answers.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Completed Answer",
                "verbose_name_plural": "Completed Answers",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="The country where this ideology is present or relevant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="cities_light.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology being contextualized.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific region within a country (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="cities_light.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The religion associated with this ideology in this context.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideology_associations",
                        to="ideology.religion",
                        verbose_name="Religion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Association",
                "verbose_name_plural": "Ideology Associations",
            },
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Countries where this ideology is explicitly present.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="cities_light.country",
                verbose_name="Associated Countries",
            ),
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific regions where this ideology is explicitly present.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="cities_light.region",
                verbose_name="Associated Regions",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the conditioner or variable.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed explanation of what this conditioner measures or defines within an ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "Boolean (Yes/No)"),
                            ("categorical", "Categorical (Selection)"),
                            ("scale", "Scale (Numeric Range)"),
                            ("numeric", "Numeric Value"),
                            ("text", "Free Text"),
                        ],
                        default="categorical",
                        help_text="Defines the format of the data expected for this conditioner.",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "accepted_values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        help_text="List of valid options if the type is 'Categorical' (comma-separated in admin). Leave empty for other types.",
                        null=True,
                        verbose_name="Accepted Values",
                    ),
                ),
                (
                    "abstraction_complexity",
                    models.ForeignKey(
                        help_text="The complexity level that groups these conditioners.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioners",
                        to="ideology.ideologyabstractioncomplexity",
                        verbose_name="Abstraction Complexity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Conditioner",
                "verbose_name_plural": "Ideology Conditioners",
                "ordering": ["abstraction_complexity", "name"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title or source name (e.g., Book Title, Article Headline, Author Name).",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Contextual details or specific quotes relevant to the ideology.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to the source material, if available online.",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology supported or explained by this reference.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology reference",
                "verbose_name_plural": "Ideology references",
            },
        ),
        migrations.CreateModel(
            name="IdeologySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title of the thematic section (e.g., 'Economics', 'Social Structure').",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A summary of the topics and concepts covered in this section.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Visual representation for this section. SVG or PNG formats are recommended.",
                        null=True,
                        upload_to=core.helpers.storage_helpers.handle_storage,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "abstraction_complexity",
                    models.ForeignKey(
                        help_text="The complexity level that groups these sections.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="ideology.ideologyabstractioncomplexity",
                        verbose_name="Abstraction Complexity",
                    ),
                ),
                (
                    "conditioned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. Specifies a conditioner that determines the visibility or applicability of this section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_sections",
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioned By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Section",
                "verbose_name_plural": "Ideology Sections",
                "ordering": ["abstraction_complexity", "name"],
            },
        ),
        migrations.CreateModel(
            name="IdeologyAxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name of the axis (e.g., 'Economic Freedom').",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of what this axis measures.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "left_label",
                    models.CharField(
                        help_text="Label for the start or minimum value of the axis (e.g., 'Total Control').",
                        max_length=255,
                        verbose_name="Left Label (0%)",
                    ),
                ),
                (
                    "right_label",
                    models.CharField(
                        help_text="Label for the end or maximum value of the axis (e.g., 'Total Liberty').",
                        max_length=255,
                        verbose_name="Right Label (100%)",
                    ),
                ),
                (
                    "conditioned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. A conditioner that determines if this axis is relevant.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_axes",
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioned By",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="The thematic section this axis belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axes",
                        to="ideology.ideologysection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Axis",
                "verbose_name_plural": "Ideology Axes",
                "ordering": ["section", "name"],
                "unique_together": {("section", "name")},
            },
        ),
        migrations.AddField(
            model_name="ideology",
            name="associated_religions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Religions linked to this ideology.",
                related_name="ideologies",
                through="ideology.IdeologyAssociation",
                to="ideology.religion",
                verbose_name="Associated Religions",
            ),
        ),
        migrations.CreateModel(
            name="IdeologyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        help_text="The ideology to which this tag belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The specific tag to associate with the ideology.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideology_assignments",
                        to="ideology.tag",
                        verbose_name="Tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology tag",
                "verbose_name_plural": "Ideology tags",
            },
        ),
        migrations.AddField(
            model_name="ideology",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this ideology.",
                related_name="ideologies",
                through="ideology.IdeologyTag",
                to="ideology.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="AxisAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The position on the axis. Must be between -1.0 (Extreme Left) and 1.0 (Extreme Right).",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Position Value",
                    ),
                ),
                (
                    "margin_left",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Acceptable deviation towards the left side for this ideology definition.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                        verbose_name="Left Margin Tolerance",
                    ),
                ),
                (
                    "margin_right",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Acceptable deviation towards the right side for this ideology definition.",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                        verbose_name="Right Margin Tolerance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who obtained this result. Leave empty if this is defining an ideology.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ideology defined by this position. Leave empty if this is a user's result.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axis_definitions",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "axis",
                    models.ForeignKey(
                        help_text="The specific axis being measured.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ideology.ideologyaxis",
                        verbose_name="Axis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Axis Answer",
                "verbose_name_plural": "Axis Answers",
                "ordering": ["axis", "ideology", "user"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ideology__isnull", False)),
                        fields=("ideology", "axis"),
                        name="unique_ideology_axis_position",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "axis"),
                        name="unique_user_axis_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ideology__isnull", True), ("user__isnull", False)
                            ),
                            models.Q(
                                ("ideology__isnull", False), ("user__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="axis_answer_owner_xor_constraint",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConditionerAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        help_text="The value chosen. Must match one of the 'accepted_values' defined in the conditioner.",
                        max_length=255,
                        verbose_name="Answer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who provided this answer. Leave empty if this is defining an ideology.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioner_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "ideology",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ideology defined by this answer. Leave empty if this is a user's answer.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioner_definitions",
                        to="ideology.ideology",
                        verbose_name="Ideology",
                    ),
                ),
                (
                    "conditioner",
                    models.ForeignKey(
                        help_text="The question or variable being answered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ideology.ideologyconditioner",
                        verbose_name="Conditioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conditioner Answer",
                "verbose_name_plural": "Conditioner Answers",
                "ordering": ["conditioner", "ideology", "user"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ideology__isnull", False)),
                        fields=("ideology", "conditioner"),
                        name="unique_ideology_conditioner_answer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "conditioner"),
                        name="unique_user_conditioner_answer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ideology__isnull", True), ("user__isnull", False)
                            ),
                            models.Q(
                                ("ideology__isnull", False), ("user__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="conditioner_answer_owner_xor_constraint",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ideologyassociation",
            constraint=models.UniqueConstraint(
                fields=("ideology", "country", "region", "religion"),
                name="unique_ideology_context_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="ideologyassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country__isnull", False),
                    ("region__isnull", False),
                    ("religion__isnull", False),
                    _connector="OR",
                ),
                name="ideology_association_has_at_least_one_context",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ideologytag",
            unique_together={("tag", "ideology")},
        ),
    ]
