# Generated by Django 6.0 on 2026-01-14 17:01

import django.core.validators
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="axisanswer",
            name="axis_answer_lower_bound_check",
        ),
        migrations.RemoveConstraint(
            model_name="axisanswer",
            name="axis_answer_upper_bound_check",
        ),
        migrations.AddField(
            model_name="axisanswer",
            name="is_indifferent",
            field=models.BooleanField(
                default=False,
                help_text="If true, the user is indifferent to this axis (no value).",
                verbose_name="Is Indifferent",
            ),
        ),
        migrations.AlterField(
            model_name="axisanswer",
            name="margin_left",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Positive magnitude of deviation allowed towards the left. (Value - Margin Left >= -100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Left Margin Tolerance",
            ),
        ),
        migrations.AlterField(
            model_name="axisanswer",
            name="margin_right",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Positive magnitude of deviation allowed towards the right. (Value + Margin Right <= 100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Right Margin Tolerance",
            ),
        ),
        migrations.AlterField(
            model_name="axisanswer",
            name="value",
            field=models.IntegerField(
                blank=True,
                help_text="The position on the axis. Must be between -100 (Extreme Left) and 100 (Extreme Right).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-100),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Position Value",
            ),
        ),
        migrations.AddConstraint(
            model_name="axisanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__isnull", True),
                    (
                        "value__gte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("margin_left"), "-", models.Value(100)
                        ),
                    ),
                    _connector="OR",
                ),
                name="axis_answer_lower_bound_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="axisanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__isnull", True),
                    (
                        "value__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.Value(100), "-", models.F("margin_right")
                        ),
                    ),
                    _connector="OR",
                ),
                name="axis_answer_upper_bound_check",
            ),
        ),
    ]
