# Generated by Django 6.0 on 2026-01-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideologyabstractioncomplexity",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Boolean to show if the level is visible or not in the frontend. Used to hide a level that is in progress or only available for certain users.",
                verbose_name="Visible",
            ),
        ),
    ]
