# Generated by Django 6.0 on 2026-01-15 14:53

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ideology",
            "0003_ideologyaxisdefinition_ideologyconditionerdefinition_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeologyConditionerConditioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of this condition rule.",
                        max_length=128,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_es",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the logic applied in this rule.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "condition_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_es",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "condition_values_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of values that satisfy this condition (e.g. ['Spain']). Must match values in the source conditioner.",
                        null=True,
                        verbose_name="Trigger Values",
                    ),
                ),
                (
                    "source_conditioner",
                    models.ForeignKey(
                        help_text="The conditioner determining visibility.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_conditioner_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Source Conditioner",
                    ),
                ),
                (
                    "target_conditioner",
                    models.ForeignKey(
                        help_text="The conditioner being conditioned.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_rules",
                        to="ideology.ideologyconditioner",
                        verbose_name="Target Conditioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideology Conditioner Conditioner",
                "verbose_name_plural": "Ideology Conditioner Conditioners",
                "ordering": ["target_conditioner", "name"],
                "unique_together": {
                    ("target_conditioner", "source_conditioner", "name"),
                    ("target_conditioner", "source_conditioner", "name_en"),
                    ("target_conditioner", "source_conditioner", "name_es"),
                },
            },
        ),
        migrations.AddField(
            model_name="ideologyconditioner",
            name="conditioners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditioners that determine the visibility of this conditioner.",
                related_name="conditioned_by",
                through="ideology.IdeologyConditionerConditioner",
                to="ideology.ideologyconditioner",
                verbose_name="Conditioners",
            ),
        ),
    ]
