# Generated by Django 6.0 on 2026-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[("internal", "Internal"), ("google", "Google")],
                default="internal",
                help_text="The provider used for the user authentication/registration.",
                max_length=20,
                verbose_name="Auth Provider",
            ),
        ),
    ]
