# Generated by Django 6.0 on 2026-01-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="atlas_onboarding_completed",
            field=models.BooleanField(
                default=False,
                help_text="Field showing whether or not the user has completed the atlas onboarding.",
                verbose_name="Atlas Onboarding Completed",
            ),
        ),
    ]
