# Generated by Django 6.0 on 2026-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_auth_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Secret token used for email verification.",
                null=True,
                unique=True,
                verbose_name="Verification UUID",
            ),
        ),
    ]
