from .axis_answer_admin import *
from .completed_answer_admin import *
from .conditioner_answer_admin import *
from .ideology_abstraction_complexity_admin import *
from .ideology_association_admin import *
from .ideology_axis_admin import *
from .ideology_conditioner_admin import *
from .ideology_admin import *
from .ideology_reference_admin import *
from .ideology_section_admin import *
from .ideology_tag_admin import *
from .religion_admin import *
from .tag_admin import *
